# This file was generated by liblab | https://liblab.com/

from weatherstack import Weatherstack, Environment

sdk = Weatherstack(base_url=Environment.DEFAULT.value)

result = sdk.current.current_location(access_key="YOUR_ACCESS_KEY", query="New Delhi")

print(result)
