name: Publish to PyPI

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'  # Replace with your Python version

      - name: Install pip and pip-tools
        run: |
          python -m ensurepip
          python -m pip install --upgrade pip
          python -m pip install pip-tools

      - name: Build package
        run: python -m build

      - name: Publish to PyPI
        env:
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python -m pip install twine
          python -m twine upload --skip-existing --username __token__ --password $TWINE_PASSWORD dist/*

      - name: Cleanup
        run: rm -rf dist/
